# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  cypress: cypress-io/cypress@1
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm install & npm run build' # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start' # start server before running tests
          wait-on: 'http://localhost:4200'
